version: 2

before:
  hooks:
    - go generate ./...
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

sboms:
  - id: archive
    artifacts: archive
  - id: source
    artifacts: source

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - --yes
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
    artifacts: checksum

nfpms:
  - vendor: Forensic Examiner
    homepage: forensic-examiner.eu
    maintainer: Christian Uhsat <christian@uhsat.de>
    description: |-
      Forensic Examiner.
      The Swiss Army Knife for examining text files.
    license: GPL-3.0
    formats:
      - apk
      - deb
      - rpm
    provides:
      - fox
    suggests:
      - ollama
    section: utils
    contents:
      - src: ./LICENSE.md
        dst: /usr/share/doc/fox/copyright
        file_info:
          mode: 0644
