version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7

nfpms:
  - vendor: Hinterland Forensics
    homepage: https://github.com/cuhsat/fox
    maintainer: Christian Uhsat <christian@uhsat.de>
    description: |-
      The Swiss Army Knife for examining text files.
    #file_name_template: "{{ .ConventionalFileName }}"
    license: GPL-3.0
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    section: utils
    contents:
      # - src: ./completions/nfpm.bash
      #   dst: /usr/share/bash-completion/completions/nfpm
      #   file_info:
      #     mode: 0644
      # - src: ./completions/nfpm.zsh
      #   dst: /usr/share/zsh/vendor-completions/_nfpm
      #   file_info:
      #     mode: 0644
      # - src: ./manpages/nfpm.1.gz
      #   dst: /usr/share/man/man1/nfpm.1.gz
      #   file_info:
      #     mode: 0644
      - src: ./LICENSE.md
        dst: /usr/share/doc/fox/copyright
        file_info:
          mode: 0644

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

sboms:
  - id: archive
    artifacts: archive
  - id: source
    artifacts: source

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - --yes
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
    artifacts: checksum
