site_name: Forensic Examiner
site_description: The Swiss Army Knife for examining text files.
site_author: Christian Uhsat
site_url: https://forensic-examiner.eu

repo_name: github.com/cuhsat/fox
repo_url: https://github.com/cuhsat/fox

remote_branch: docs

copyright: 🦊 forensic-examiner.eu is released under the GPL-3.0

nav:
  - Home: index.md

  - Basics:
    - Install: basics/install.md
    - Tutorial: basics/tutorial.md
    - Usage:
        - fox: basics/usage/fox.md
        - fox compare: basics/usage/compare.md
        - fox counts: basics/usage/counts.md
        - fox deflate: basics/usage/deflate.md
        - fox entropy: basics/usage/entropy.md
        - fox hash: basics/usage/hash.md
        - fox strings: basics/usage/strings.md

  - Features:
    - Loader: features/loader.md
    - Memory: features/memory.md

    - Files:
        - csv: features/files/csv.md
        - json: features/files/json.md
        - evtx: features/files/evtx.md
        - journal: features/files/journal.md

    - Utils:
        - Deflate: features/utils/deflate.md
        - Compare: features/utils/compare.md
        - Hashes: features/utils/hashes.md
        - Strings: features/utils/strings.md
        - Entropy: features/utils/entropy.md
        - Counts: features/utils/counts.md

    - AI:
      - Agent: features/ai/agent.md

    - UI:
      - Terminal: features/ui/terminal.md
      - Unicode: features/ui/unicode.md
      - Keymap:  features/ui/keymap.md
      - Mode:
        - Less: features/ui/mode/less.md
        - Grep: features/ui/mode/grep.md
        - Hex: features/ui/mode/hex.md
        - Fox: features/ui/mode/fox.md

    - Evidence: features/evidence.md

  - Plugins: plugins.md
  - Themes: themes.md
  - Building: building.md
  - License: license.md

theme:
  name: material
  logo: fox.svg
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  favicon: fox.ico
  features:
    - header.autohide
    - navigation.path
    - navigation.indexes
    - search.suggest
    - search.highlight
  palette:
    primary: custom
    accent: custom

extra:
  homepage: https://forensic-examiner.eu
  generator: false
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:christian@uhsat.de
      name: Mail

    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/cuhsat
      name: LinkedIn

    - icon: fontawesome/brands/github
      link: https://github.com/cuhsat
      name: GitHub

extra_css:
  - styles/fox.css

plugins:
  - search
  - privacy
  - offline
