Output fox.gif

Set CursorBlink false
Set TypingSpeed 150ms
Set Padding 0

#Type "cd .. && go run main.go test/testdata/nist/HackingCase.E01 -S" Enter Sleep 2s
#
#F7 Type "evtx" Enter Sleep 3s

Type "cd .. && go run main.go test/testdata/zip/events.zip -S" Enter Sleep 2s

Tab Sleep 3s

Ctrl+F Type "462[4|5]" Enter Sleep 3s
Ctrl+F Type "ssh" Enter Sleep 3s

Ctrl+W Sleep 3s

Space Sleep 1s
Space Sleep 1s
Space Sleep 1s

Ctrl+E Type "analyse this" Enter Sleep 18s
Ctrl+S Enter Sleep 3s
