# available model names:
#
#  https://ollama.com/library
#
[ai]
model = '' # disabled
num_ctx = 4096
seed = 8211
temp = '0.2'
topk = 10
topp = '0.5'

# available theme names:
#
#  examiner-dark
#  examiner-light
#  catppuccin-latte
#  catppuccin-frappe
#  catppuccin-macchiato
#  catppuccin-mocha
#  solarized-dark
#  solarized-light
#  vscode-dark
#  vscode-light
#  monokai
#  darcula
#  nord
#  matrix
#  monochrome
#
[ui]
theme = 'examiner-dark'

[ui.state]
n = true
t = false
w = false
