# Available variables (all):
#
#  FILE    file path
#  BASE    base path
#  TEMP    new temporary folder
#
# Available variables (only hotkey):
#
#  INPUT   user input
#
[auto.info]
name = 'target-info'
path = '.*\.(dd|img|raw|ad1|asdf|E0?|00?)'
exec = [
  'target-info "FILE"'
]

# Available hotkeys:
#
#  F8 to F12
#
[hotkey.f8]
name = 'target-query'
mode = 'query'
exec = [
  'target-query -j -f "INPUT" "BASE"'
]
