# available variables:
#
#  FILE path
#  BASE path
#  TEMP folder (will be created)
#
# additional variables for hotkeys:
#
#  INPUT by user
#
[auto.info]
name = 'target-info'
path = '.*\.(dd|img|raw|ad1|asdf|E0?|00?)'
exec = [
  'target-info "FILE"'
]

# available hotkeys:
#
#  F8 to F12
#
[hotkey.f8]
name = 'target-query'
mode = 'query'
exec = [
  'target-query -j -f "INPUT" "BASE"'
]
