[theme.custom]
name = 'custom'
terminal = [ 0xFFFFFF, 0x000000 ] # base
surface0 = [ 0xFFFFFF, 0x000000 ] # info panes
surface1 = [ 0xFFFFFF, 0x000000 ] # info areas
surface2 = [ 0xFFFFFF, 0x000000 ] # current file
surface3 = [ 0xFFFFFF, 0x000000 ] # current mode
overlay0 = [ 0xFFFFFF, 0x000000 ] # failure messages
overlay1 = [ 0xFFFFFF, 0x000000 ] # success messages
subtext0 = [ 0xFFFFFF, 0x000000 ] # navigation items
subtext1 = [ 0xFFFFFF, 0x000000 ] # separator lines
subtext2 = [ 0xFFFFFF, 0x000000 ] # highlights
